name: memory_game_web
description: A memory game written for the web.
version: 0.5.0
homepage: https://memorygameweb.herokuapp.com
author: Jermaine Oppong

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  shelf: any
  shelf_static: any

dev_dependencies:
  build_runner: ^0.8.7
  build_web_compilers: ^0.4.0
